language: r
sudo: true
cache: packages
warnings_are_errors: false

env:
  global:
    - BIOC_USE_DEVEL="FALSE"
    - R_BUILD_ARGS="--no-build-vignettes --no-manual"
    - R_CHECK_ARGS="--no-build-vignettes --no-manual --timings"
    - _R_CHECK_TIMINGS_="0"

r:
  - release

r_build_args: --no-build-vignettes --no-manual
r_check_args: --no-build-vignettes --no-manual --timings

r_packages: 
  - ggplot2
  - ggforce
  - R6
  - magrittr
  - dplyr
  - purrr
  - stats
  - stringr
  - scales
  - rlang
  - httr
  - openxlsx
  - reshape2
  - reactable
  - msigdbr
  - kableExtra
  - rmarkdown
  - igraph
  - visNetwork

bioc_required: true
